#!/usr/bin/env python3
"""
Demonstration script showing generated systemd-networkd files

This simulates what the network-config bbclass generates during the build process.
"""

import json
from jinja2 import Template
from pathlib import Path

# Simple configuration
config = {
    "version": "1.0",
    "hostname": "demo-device",
    "interfaces": [
        {
            "name": "eth0",
            "kind": "ethernet",
            "description": "Primary Ethernet",
            "dhcp4": True,
            "mtu": 1500
        },
        {
            "name": "eth1",
            "kind": "ethernet",
            "description": "Secondary Link",
            "mtu": 1500
        },
        {
            "name": "vlan10",
            "kind": "vlan",
            "description": "Management VLAN",
            "id": 10,
            "link": "eth0",
            "ipv4": ["192.168.10.100/24"],
            "gateway4": "192.168.10.1",
            "mtu": 1500
        },
        {
            "name": "bond0",
            "kind": "bond",
            "description": "Redundancy Bond",
            "members": ["eth1"],
            "mode": "active-backup",
            "miimon": 100,
            "dhcp4": True
        }
    ]
}

# Templates
network_template = """# Auto-generated by Yocto network-config class
# Configuration for interface: {{ interface.name }}
# Do NOT edit manually - changes will be overwritten!

[Match]
Name={{ interface.name }}

[Link]
{% if interface.get('mtu') %}
MTUBytes={{ interface.mtu }}
{% endif %}
{% if interface.get('description') %}
Alias={{ interface.description }}
{% endif %}

[Network]
{% if interface.get('dhcp4') %}
DHCP=ipv4
{% endif %}
{% if interface.get('ipv4') %}
{% for addr in interface.ipv4 %}
Address={{ addr }}
{% endfor %}
{% endif %}
{% if interface.get('gateway4') %}
Gateway={{ interface.gateway4 }}
{% endif %}
"""

netdev_template = """# Auto-generated by Yocto network-config class
# Virtual interface: {{ interface.name }} (type: {{ kind }})

{% if kind == 'vlan' %}
[NetDev]
Name={{ interface.name }}
Kind=vlan
{% if interface.get('description') %}
Description={{ interface.description }}
{% endif %}

[VLAN]
Id={{ interface.get('id', 0) }}

{% elif kind == 'bond' %}
[NetDev]
Name={{ interface.name }}
Kind=bond
{% if interface.get('description') %}
Description={{ interface.description }}
{% endif %}

[Bond]
Mode={{ interface.get('mode', 'balance-alb') }}
MIIMonitorSec={{ interface.get('miimon', 100) }}ms
{% endif %}
"""

def generate_files():
    """Generate systemd-networkd configuration files."""
    print("=" * 70)
    print("DEMONSTRATION: Generated systemd-networkd Configuration Files")
    print("=" * 70)
    
    index = 10
    files_generated = []
    
    for interface in config.get('interfaces', []):
        name = interface.get('name')
        kind = interface.get('kind', 'ethernet')
        
        print(f"\n\n📁 Interface: {name} ({kind})")
        print("-" * 70)
        
        # Generate .network file
        template = Template(network_template)
        network_content = template.render(interface=interface, index=index)
        filename = f"{index:02d}-{name}.network"
        files_generated.append((filename, network_content))
        
        print(f"\n✅ Generated: {filename}")
        print("\n" + network_content)
        
        # Generate .netdev file for virtual interfaces
        if kind in ('vlan', 'bond'):
            template = Template(netdev_template)
            netdev_content = template.render(interface=interface, kind=kind, index=index)
            filename = f"{index:02d}-{name}.netdev"
            files_generated.append((filename, netdev_content))
            
            print(f"\n✅ Generated: {filename}")
            print("\n" + netdev_content)
        
        index += 1
    
    print("\n\n" + "=" * 70)
    print("SUMMARY: Files Generated for /etc/systemd/network/")
    print("=" * 70)
    
    for filename, _ in files_generated:
        print(f"  • {filename}")
    
    print(f"\nTotal files: {len(files_generated)}")
    print("=" * 70)
    print("\n✨ At runtime, systemd-networkd reads these files and configures the network")
    print("   No runtime processing needed - everything is pre-computed at build time!")
    print("\n")


if __name__ == "__main__":
    try:
        generate_files()
    except ImportError as e:
        print(f"Error: Missing dependency: {e}")
        print("Install with: pip install jinja2")
