# this distribution configuration file is used 
# to build a custom image with Python support for the Simpat project.
require conf/distro/poky.conf

DISTRO = "poky-simpat"
DISTRO_NAME = "Poky Simpat Distribution"

# Ajout des packages Python dans l'image par défaut
DISTRO_FEATURES:append = " python3 systemd"

#remove
DISTRO_FEATURES:remove = " sysvinit"

# Ajout des packages dans toutes les images
IMAGE_INSTALL:append = " python3 python3-pip python3-modules "

VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""