# Serveur NTP personnalisé
server 192.168.10.20 iburst

# Fallback public
pool pool.ntp.org iburst

# Correction rapide au boot
makestep 1.0 3

# Fichier de dérive
#driftfile /var/lib/chrony/drift

# Logs
#logdir /var/log/chrony